all:
	cd ../Maths-MPSI-Cours/29-Poly;make clean;make get;make;make;make;cp cours.pdf ../../Commun/maths.pdf;make clean
	# cd ../Maths-MPSI-Cours/29-Poly;make clean;make get;make tome-pdf;make tome-pdf;make tome-pdf;cp cours1.pdf ../../Commun/maths1.pdf;cp cours2.pdf ../../Commun/maths2.pdf;cp cours3.pdf ../../Commun/maths3.pdf;cp cours4.pdf ../../Commun/maths4.pdf;cp cours5.pdf ../../Commun/maths5.pdf;make clean
	cd ../Info-MP2I-Cours/20-Poly;make clean;make get;make;make;make;cp cours.pdf ../../Commun/info.pdf;make clean
	cd ../Info-MP2I-Cours/20-Poly;make clean;make get;make python;make python;make python;cp cours-python.pdf ../../Commun/python.pdf;make clean
maths:
	cd ../Maths-MPSI-Cours/29-Poly;make clean;make get;make;make;make;cp cours.pdf ../../Commun/maths.pdf;make clean
maths-sup:
	cd ../Maths-MPSI-Cours/29-PolySup;make clean;make get;make;make;make;cp cours.pdf ../../Commun/maths-sup.pdf;make clean
maths-tome:
	cd ../Maths-MPSI-Cours/29-Poly;make clean;make get;make tome-pdf;make tome-pdf;make tome-pdf;cp cours1.pdf ../../Commun/maths1.pdf;cp cours2.pdf ../../Commun/maths2.pdf;cp cours3.pdf ../../Commun/maths3.pdf;cp cours4.pdf ../../Commun/maths4.pdf;cp cours5.pdf ../../Commun/maths5.pdf;make clean
info:
	cd ../Info-MP2I-Cours/20-Poly;make clean;make get;make;make;make;cp cours.pdf ../../Commun/info.pdf;make clean
python:
	cd ../Info-Commun-Cours/09-Poly;make clean;make get;make;make;make;cp cours-python.pdf ../../Commun/cours-python.pdf;make clean
desktop:
	mv maths.pdf ~/Desktop
	mv maths1.pdf ~/Desktop
	mv maths2.pdf ~/Desktop
	mv maths3.pdf ~/Desktop
	mv maths4.pdf ~/Desktop
	mv maths5.pdf ~/Desktop
	mv info.pdf ~/Desktop
	mv python.pdf ~/Desktop
